
---
include:
  # left
  - board: seeeduino_xiao_ble
    shield: cygnus_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # right
  - board: seeeduino_xiao_ble
    shield: cygnus_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n


  # zongle (nrf52833 based)
  - board: seeeduino_xiao_ble
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    shield: cygnus_dongle 

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset

  # settings reset for zongle (nrf52833 based)
  - board: seeeduino_xiao_ble
    shield: settings_reset


